package it.polimi.ingsw.Server.Model.Match;

import it.polimi.ingsw.Server.Model.Cards.BuildingCards.BuildingCard;
import it.polimi.ingsw.Server.Model.Cards.BuildingCards.BuildingEffects.BuildingEffect;
import it.polimi.ingsw.Server.Model.Cards.BuildingCards.BuildingEffects.DoubleBuilderPoints;
import it.polimi.ingsw.Server.Model.Cards.BuildingCards.BuildingEffects.ExtraCardPick;
import it.polimi.ingsw.Server.Model.Cards.BuildingCards.BuildingEffects.ExtraFoodTurnEnd;
import it.polimi.ingsw.Server.Model.Cards.BuildingCards.BuildingEffects.ShamanicShield;
import it.polimi.ingsw.Server.Model.Cards.CharacterCards.CharacterCard;
import it.polimi.ingsw.Server.Model.Cards.CharacterCards.InventionIcon;
import it.polimi.ingsw.Server.Model.Cards.CharacterCards.Inventor;
import it.polimi.ingsw.Server.Model.Cards.CharacterCards.Shaman;


import java.util.*;
import java.util.stream.Collectors;

/**
 * Represents a player's Tribe in the game, managing their collection of cards and active effects.
 * <p>
 * The Tribe acts as the central hub for a player's engine-building mechanics. It stores all acquired
 * {@link CharacterCard}s and {@link BuildingCard}s, dynamically calculating:
 * <ul>
 * <li>Resource discounts (e.g., sustenance and building costs)</li>
 * <li>Game phase bonuses (e.g., extra card picks, food generation during specific events)</li>
 * <li>End-game prestige points (e.g., multiplier effects, character sets, and artist pairs)</li>
 * </ul>
 * </p>
 * <p>
 * It also seamlessly tracks the occurrences of specific character classes (such as Hunters, Gatherers,
 * or Shamans) to facilitate set-collection scoring and resolve complex building synergies during the match.
 * </p>
 */
public class Tribe {
    private final List<BuildingCard> buildingCardList;
    private final List<CharacterCard> characterCardList;
    private final Map<String, Integer> characterCounter = new HashMap<>();

    //constructor for testing
    public Tribe(List<BuildingCard> buildingCardList, List<CharacterCard> characterCardList) {
        this.buildingCardList = new ArrayList<>(buildingCardList);
        this.characterCardList = new ArrayList<>(characterCardList);
    }

    /**
     * Constructs an empty tribe with no buildings and no characters.
     */
    public Tribe() {
        this.buildingCardList = new ArrayList<>();
        this.characterCardList = new ArrayList<>();
    }

    public List<CharacterCard> getCharacterCardList(){
        return this.characterCardList;
    }

    public List<BuildingCard> getBuildingCardList() {
        return buildingCardList;
    }

    //adders for lists of the tribe

    /**
     * Adds a character card to the tribe's collection and notifies all owned
     * buildings to trigger any associated passive effects (e.g., food on card pick).
     *
     * @param character the {@link CharacterCard} to add
     * @return the total food bonus generated by building effects upon adding this character
     */
    public int addCharacter(CharacterCard character){
        characterCardList.add(character);
        //this will update the private counters of the building effect if needed
        return buildingCardList.stream()
                .mapToInt(b -> b.getEffect().onCardPickFoodBonus(this))
                .sum();
    }

    /**
     * Adds a building card to the tribe's collection and initializes its
     * passive effect by passing the current state of the tribe.
     *
     * @param building the {@link BuildingCard} to add
     */
    public void addBuilding(BuildingCard building){
        buildingCardList.add(building);
        if (building.getEffect() != null) {
            building.getEffect().onBuildingAcquired(this); //this will update the private counters of the building effect if needed
        }
    }


    //getters


    public int getTotalCharactersCount(){
        return characterCardList.size();
    }



    //methods for buildings effects

    /**
     * Calculates the total number of additional card picks available to the tribe,
     * based on the cumulative effects of all owned building cards.
     * @see ExtraCardPick
     * @return the total number of extra card picks
     */
    public int getExtraCardPicksCount(){
        return buildingCardList.stream()
                .map(BuildingCard::getEffect)
                .mapToInt(BuildingEffect::howManyExtraCardPicks)
                .sum();
    }

    public int getExtraUpCardPicksCount(){
        return buildingCardList.stream()
                .map(BuildingCard::getEffect)
                .mapToInt(BuildingEffect::getExtraUpCardPicks)
                .sum();
    }

    public int getExtraDownCardPicksCount(){
        return buildingCardList.stream()
                .map(BuildingCard::getEffect)
                .mapToInt(BuildingEffect::getExtraDownCardPicks)
                .sum();
    }

    /**
     * Calculates the total extra food bonus for the Turn Order phase
     * provided by all the building cards owned by the tribe.
     *
     * @see ExtraFoodTurnEnd
     * @see Player
     * @return the total extra food bonus
     */
    public int getExtraTurnOrderBonus(){
        return buildingCardList.stream()
                .map(BuildingCard::getEffect)
                .mapToInt(BuildingEffect::getExtraTurnOrderFoodBonus)
                .sum();
    }

    //methods for end game buildings effects
    /**
     * Calculates the total end-game prestige points awarded by builder characters,
     * applying any multipliers provided by the tribe's building cards.
     * @see DoubleBuilderPoints
     * @return the final calculated prestige points from builders
     */
    public int getFinalBuilderPoints() { //this will be called by the gameState during the EndGame phase to compute PP from builders
        int basePoints = characterCardList.stream()
                .mapToInt(CharacterCard::getBuilderPoints)//only builders have this != 0
                .sum();

        double multiplier = 1.0; //default multiplier
        for (BuildingCard b : buildingCardList) { //if there are buildings with multipliers, cumulate the multipliers
            multiplier *= b.getEffect().getFinalBuilderPointsMultiplier();
        }
        return (int) (basePoints * multiplier);
    }


    /**
     * Calculates the total final prestige points granted by all building cards in the tribe.
     * * @return the sum of base prestige points from all owned buildings
     */
    public int getFinalBuildingPrestigePoints() {
        return buildingCardList.stream()
                .mapToInt(BuildingCard::getFinalPrestigePoints)
                .sum();
    }


    /**
     * Calculates the cumulative end-game prestige points granted by all
     * building effects, excluding multipliers which are handled separately for obvious reasons.
     *
     * @return the sum of flat end-game bonus points from buildings
     */
    public int calculateEndGameBuildingEffects(){
        return buildingCardList.stream()
                        .mapToInt(b -> b.getEffect().onEndOfGame(this))
                        .sum();
    }



    //methods for events that take into account buildings effects


    /**
     * Calculates the total food discount for the Sustenance event,
     * combining the discounts provided by both Gatherer characters and Building cards.
     *
     * @return the total sustenance discount
     */
    public int getTotalSustenanceDiscount() {
        int gathererDiscount = characterCardList.stream()
                .mapToInt(CharacterCard::getFoodDiscount)
                .sum();

        int buildingDiscount = buildingCardList.stream()
                .mapToInt(buildingCard -> buildingCard.getEffect().onSustenanceEvent(this))
                .sum();

        return gathererDiscount + buildingDiscount;
    }

    /**
     * cycles through all buildings of the player's tribe
     * each giving its contribution to onHuntEvent food bonus
     * @return sum of all buildings' food
     */
    public int getTotalBuildingFoodOnHuntEvent(){
        return buildingCardList.stream()
                .mapToInt(buildingCard -> buildingCard.getEffect().getFoodOnHuntEvent(this))
                .sum();
    }

    /**
     * cycles through all buildings of the player's tribe
     * each giving its contribution to onHuntEvent prestige points bonus
     * @return sum of all buildings' prestige points
     */
    public int getTotalBuildingPointsOnHuntEvent(){
        return buildingCardList.stream()
                .mapToInt(buildingCard -> buildingCard.getEffect().getPointsOnHuntEvent(this))
                .sum();
    }

    /**
     * cycles through all buildings of the player's tribe
     * each giving shamanic stars
     * @return the sum of additional shamanic stars from all buildings
     */
    public int getAdditionalShamanicStars() {
        return buildingCardList.stream()
                .mapToInt(b -> b.getEffect().getExtraShamanicStars())
                .sum();
    }

    /**
     * Applies all building effects to the prestige gain during the Shamanic Ritual event.
     * <p>
     * Each {@link BuildingCard} in the tribe can modify the base gain through its
     * method. Effects are applied sequentially: the output of one effect becomes
     * the input of the next.
     * </p>
     * <p>
     * {@code maxGroupCount} is required to distinguish between a unique leader
     * (strict majority) which affects buildings
     * such as {@link DoubleBuilderPoints}
     * </p>
     *
     * @param baseGain      the base prestige gain as defined by the event card
     * @param ownerStars    the effective star count of this tribe (base + building bonuses)
     * @param maxStars      the highest effective star count among all players
     * @param maxGroupCount the number of players sharing the maximum star count
     * @return the final prestige gain after all building effects have been applied
     */

    public int applyShamanicGain(int baseGain, int ownerStars, int maxStars,
                                 int maxGroupCount) { //MAX GROUP COUNT for it rules
        int currentGain = baseGain;
        for (BuildingCard b : buildingCardList)  //apply the effect on every building
            currentGain = b.getEffect().onShamanicGain(currentGain, ownerStars, maxStars, maxGroupCount);
        return currentGain;
    }

    /**
     * Applies all building effects to the prestige loss during the Shamanic Ritual event.
     * <p>
     * Each {@link BuildingCard} in the tribe can modify the base loss through its
     * method. Effects are applied sequentially: the output of one effect becomes
     * the input of the next.
     * </p>
     * <p>
     * This phase is resolved separately from the gain phase to allow effects such as
     * {@link ShamanicShield}
     * to cancel the loss independently, which is critical during a global tie where
     * every player is in both the max and min group simultaneously.
     * </p>
     *
     * @param baseLoss   the base prestige loss as defined by the event card
     * @param ownerStars the effective star count of this tribe (base + building bonuses)
     * @param maxStars   the highest effective star count among all players
     * @param minStars   the lowest effective star count among all players
     * @return the final prestige loss after all building effects have been applied;
     *         a return value of 0 means the loss was fully absorbed (e.g. by a shield)
     */

    //during the GainShamanicEvent
    public int applyShamanicLoss(int baseLoss, int ownerStars, int maxStars, int minStars) {
        int currentLoss = baseLoss;
        for (BuildingCard b : buildingCardList)  //apply the effect on every building
            currentLoss = b.getEffect().onShamanicLoss(currentLoss, ownerStars, maxStars, minStars);
        return currentLoss;
    }

    /**
     * Returns the total shamanic stars from all {@link Shaman} cards in this tribe.
     * <p>
     * Non-shaman cards return 0 from the default {@link CharacterCard#getShamanStars()},
     * so no explicit filtering is needed.
     * </p>
     * <p>
     * Building bonuses are <em>not</em> included here — they are added separately
     * via {@link #getAdditionalShamanicStars()} inside
     * {@link it.polimi.ingsw.Server.Model.Cards.EventCards.ShamanicRitualEvent#calculate}.
     * </p>
     *
     * @return total shamanic stars, or 0 if no Shamans are present
     */

    public int getShamanStarsCount(){
        return characterCardList.stream()
                .mapToInt(CharacterCard::getShamanStars)
                .sum();
    }

    /**
     * cycles through all buildings of the player's tribe
     * each giving its value on cave painting event food bonus
     * @return the sum of all buildings' food per artist bonus
     */
    public int getBuildingArtistBonusFood(){
        return buildingCardList.stream()
                .mapToInt(buildingCard -> buildingCard.getEffect().onCavePaintingEvent(this))
                .sum();
    }

    //helpers

    /**
     * Calculates the end-game prestige bonus granted by Artist characters.
     * <p>
     * Rule: The tribe earns 10 Prestige Points for every pair of Artists.
     * </p>
     *
     * @return the calculated bonus prestige points
     */
    public int getFinalCoupleArtistBonus() {
        long artistCount = getTotalArtistCount();
        // calculate pairs (Integer division automatically floors the result)
        long artistPairs = artistCount / 2;
        // multiply by the reward (10 PP per pair)
        return (int) (artistPairs * 10); //FIXED NUMBER
    }


    /**
     * Returns the number of distinct invention icons among all {@link Inventor}
     * cards in this tribe.
     * <p>
     * Non-inventor characters return {@code null} from {@link CharacterCard#getInvention()},
     * so they are excluded by the null filter before counting distinct values.
     *
     * @return the count of distinct {@link InventionIcon} values present in the tribe,
     *         or 0 if no Inventors are present
     */

    public int getDistinctInventionsCount(){
        return (int) characterCardList.stream()
                .map(CharacterCard::getInvention)
                .filter(Objects::nonNull) //null objects are inserted by the default method of CharacterCard (all other Characters except Inventors)
                .distinct()
                .count(); //count has long output, there is a cast to int
    }

    /**
     * Returns the total number of same-invention couples among all {@link Inventor}
     * cards in this tribe.
     * <p>
     * A couple is formed by every two Inventors sharing the same {@link InventionIcon}.
     * </p>
     *
     * @return the total number of same-invention couples in the tribe,
     *         or 0 if no couples exist
     */

    public int getEqualInventionsCoupleCount(){
        return characterCardList.stream()
                .map(CharacterCard::getInvention)
                .filter(Objects::nonNull) //null objects are inserted by the default method of CharacterCard (all other Characters except Inventors)
                .collect(Collectors.groupingBy(i -> i, Collectors.counting()))//the groupingBy method creates a map <InventionIcon, Long> so it counts for each icon the number of occurrences
                .values().stream() //now there's a stream of long
                .mapToInt(count ->(int) (count/2)) //compute the couples for each Invention casting from long to int
                .sum();
    }

    /**
     * Calculates the total food discount for purchasing building cards
     * provided by all the characters in the tribe.
     *
     * @return the total building discount
     */
    public int getBuildingDiscount(){
        return characterCardList.stream()
                .mapToInt(CharacterCard::getBuildingDiscount)
                .sum();
    }

    /**
     * Returns the number of characters set of a player.
     *
     * @param setSize define how much different character cards form a set
     * @return total number of characters set of a player or 0 if no set is found
     */
    public int getFullSetsOfCharacter(int setSize) {
        int sets = 0, temp;
        Map<String, Integer> countPerCharacterType = new HashMap<>(characterCounter);

        // loop to calculate the number of sets by gradually emptying the previously created map
        while(countPerCharacterType.size() == setSize){
            Iterator<String> iterator = countPerCharacterType.keySet().iterator();
            while( iterator.hasNext()){
                String type = iterator.next();
                temp = countPerCharacterType.get(type);
                if(temp == 1){
                  iterator.remove();
                }else{
                    countPerCharacterType.put(type, temp-1);
                }
            }
            sets++;
        }
        return sets;
    }


    //counters: number of characters of a given type


    /**
     * Counts the number  of Artist cards in the Tribe
     * @return total number of Artist in the tribe
     */
    public int getTotalArtistCount(){
        return (int) characterCardList.stream()
                .mapToInt(CharacterCard::getArtistBonus)
                .filter(x -> x != 0)
                .count();
    }

    /**
     * Counts the number  of Builder cards in the Tribe
     * @return total number of Builder in the tribe
     */
    public int getTotalBuilderCount(){
        return (int) characterCardList.stream()
                .mapToInt(CharacterCard::getBuildingDiscount)
                .filter(x -> x != 0)
                .count();
    }

    /**
     * Counts the number  of Gatherer cards in the Tribe
     * @return total number of Gatherer in the tribe
     */
    public int getTotalGathererCount(){
        return (int) characterCardList.stream()
                .mapToInt(CharacterCard::getFoodDiscount)
                .filter(x -> x != 0)
                .count();
    }

    /**
     * Counts the number  of Hunter cards in the Tribe
     * @return total number of Hunter in the tribe
     */
    public int getTotalHunterCount(){
        return (int) characterCardList.stream()
                .mapToInt(CharacterCard::getFoodBonus)
                .filter(x -> x != 0)
                .count();
    }

    /**
     * Counts the number  of Inventor cards in the Tribe
     * @return total number of Inventor in the tribe
     */
    public int getTotalInventorCount(){
        return (int) characterCardList.stream()
                .map(CharacterCard::getInvention)
                .filter(Objects::nonNull)
                .count();
    }

    /**
     * Counts the number of Shaman cards in the Tribe
     * @return total number of Shaman in the tribe
     */
    public int getTotalShamanCount(){
        return (int) characterCardList.stream()
                .mapToInt(CharacterCard::getShamanStars)
                .filter(x -> x != 0)
                .count();
    }

    /**
     * Updates the internal counter tracking the occurrences of a specific character type.
     * <p>
     * This is used dynamically to track the composition of the tribe,
     * aiding in the calculation of character sets or class-specific bonuses.
     * </p>
     *
     * @param type the specific type/class of the character card being tracked (e.g., "Hunter", "Artist")
     */
    public void updateCounter(String type) {
        int count = characterCounter.getOrDefault(type, 0);
        characterCounter.put(type, count+1);
    }
}